# index:
#    path: /
#    controller: App\Controller\DefaultController::index


produits:
   path: /produits
   controller: App\Controller\ProduitController::produits
   methods: [GET]

produit:
   path: /produit/{id}
   controller: App\Controller\ProduitController::produit
   methods: [GET]

clientUtilisateurs:
   path: /client/{id}
   controller: App\Controller\UtilisateurController::getClientUtilisateurs
   methods: [GET]

detailUtilisateur:
   path: /client/{idClient}/utilisateur/{idUtilisateur}
   controller: App\Controller\UtilisateurController::detailUtilisateur
   methods: [GET]

ajoutUtilisateur:
   path: /client/{idClient}
   controller: App\Controller\UtilisateurController::ajoutUtilisateur
   methods: [POST]

deleteUtilisateur:
   path: /client/{idClient}/utilisateur/{idUtilisateur}
   controller: App\Controller\UtilisateurController::suppressionUtilisateur
   methods: [DELETE]

api_login_check:
    path: /login